apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2025-08-26T144532Z
  name: policy-exc-req-o1832u6899w-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user
    - autogen-run-as-non-root-user
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  match:
    any:
    - resources:
        kinds:
        - ReplicaSet
        names:
        - argocd-server-*
        - argocd-repo-server-*
        - argocd-applicationset-controller-*
        - argocd-dex-server-*
        - argocd-redis-*
        - argocd-notifications-controller-*
        namespaces:
        - argocd
    - resources:
        kinds:
        - Pod
        names:
        - argocd-repo-server-*
        - argocd-application-controller-*
        - argocd-server-*
        - argocd-redis-*
        - argocd-dex-server-*
        - argocd-applicationset-controller-*
        - argocd-notifications-controller-*
        namespaces:
        - argocd
    - resources:
        kinds:
        - StatefulSet
        names:
        - argocd-application-controller
        namespaces:
        - argocd
    - resources:
        kinds:
        - Deployment
        names:
        - argocd-applicationset-controller
        - argocd-repo-server
        - argocd-redis
        - argocd-notifications-controller
        - argocd-dex-server
        - argocd-server
        namespaces:
        - argocd
