apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2026-06-09T233129Z
  name: policy-exc-req-n6893m7893c-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
    - autogen-adding-capabilities
  - policyName: require-run-as-non-root-user
    ruleNames:
    - autogen-run-as-non-root-user
    - run-as-non-root-user
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
  - policyName: disallow-host-path
    ruleNames:
    - host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-adding-capabilities-strict
    - adding-capabilities-strict
    - require-drop-all
    - autogen-require-drop-all
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
    - check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - Deployment
        names:
        - nginx2
        namespaces:
        - random
    - resources:
        kinds:
        - ReplicaSet
        names:
        - nginx2-*
        namespaces:
        - random
    - resources:
        kinds:
        - Pod
        names:
        - nginx2-*
        namespaces:
        - random
