apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod-violation
  namespace: default
spec:
  containers:
  - name: privileged-container
    image: nginx:latest
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ALL
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
---
apiVersion: v1
kind: Pod
metadata:
  name: host-network-pod-violation
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: host-network-container
    image: nginx:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-violation
  namespace: default
spec:
  containers:
  - name: non-root-container
    image: nginx:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-violation
  namespace: default
spec:
  containers:
  - name: seccomp-container
    image: nginx:latest
    securityContext:
      seccompProfile:
        type: Unconfined
